# Generated by Django 5.0.1 on 2024-03-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
